### ISSUE TITLE
vulnerabilities during npm install

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-angular-samples#119]
After the ´npm install´ instructions the console show some vulnerabilities:

![screenshot_1](https://user-images.githubusercontent.com/15818783/44368843-35daf780-a4a2-11e8-9733-1d54ddcd24ab.png)

Some of these are fixed using ´npm audit fix´

**Comment by jimmyjames** [comment]
Closing since this sample has had its dependencies audited since this issue was created (https://github.com/auth0-samples/auth0-angular-samples/commit/ea59796427e0ce24abf9619b0cd1b04aa6001c57). Please open a new issue with the specific sample section and any reported vulnerabilities if you see them.
