### ISSUE TITLE
localAuthSetup always returning false on page reload

### ISSUE THREAD

**Issue by pungiish** [auth0-samples/auth0-angular-samples#175]
Angular app ( even the base sample ) redirects/logouts the user after every page reload, even if the user is logged in and localAuthSetup() is called in app.component.ts' OnInit method. On reload, the loggedIn property is always set to false.

**Comment by stevehobbsdev** [comment]
@pungiish This could be to do with your Auth0 app set up. This usually happens when you don't have an entry in the **Allowed Web Origins** setting for the Auth0 app you're using. This should be set to the origin that your Angular app is running on (e.g.: `http://localhost:4200`).

Can you please check that and let us know?

**Comment by pungiish** [comment]
@stevehobbsdev Thank you for the fast response. Yes, I added that, but since my app is running on port 3000, i used `http://localhost:3000`. I also tried adding in another route, where I usually reload from. Also tried doing that on the sample app, it still logs me out.
I'll provide a picture
![image](https://user-images.githubusercontent.com/22725524/65051065-b0f23400-d968-11e9-9ab8-b411b921a0ad.png)

**Comment by stevehobbsdev** [comment]
@pungiish Are you signing in to your app using a social connection such as Google?

If so, another thing to check is that you're not using the developer keys in your Google social connection. You should supply a set of real keys from a Google account that you own. Otherwise you do get the issue that you're seeing.

You can also verify this is the case if you instead sign in to your app using a username and password (as opposed to using a social connection), refresh the page, and it works.

**Comment by pungiish** [comment]
@stevehobbsdev Oh, that's why it didn't work then. I use Google to login.
Could you point me into the direction of where/how can I set the keys from Google?
Thanks!
