### ISSUE TITLE
can we move the web app to port 3000?

### ISSUE THREAD

**Issue by woloski** [auth0-samples/auth0-angular-samples#225]
We are creating the callback URL automatically when a user downloads a QS from the CLI and the port is fixed to localhost:3000. Can we change it instead of using 4200?

**Comment by Widcket** [comment]
@woloski, sorry I'm following. Can you please expand?

**Comment by frederikprijck** [comment]
Hi @woloski,

We could do that, I am a bit concerned about the confusion this might give to Angular users. I know it's only a port, but angular is known to run their application on `4200`, I am pretty convinced not using `4200` will confuse people as pretty much all angular docs will always refer to 4200.

I am happy to change the port to `3000`, but before doing so I wanted to check if there is a possibility to have the CLI use `4200` for Angular instead to ensure we align with the Angular defaults rather than adapt for our own tooling.

If that isn't an option, I am happy to change the port. But I wanted to verify before doing so.

**Comment by woloski** [comment]
hmmm I see. @Widcket not sure how complex would it be to change the default URL in the CLI "if Angular".

**Comment by Widcket** [comment]
@woloski not much, can squeeze it in today

**Comment by frederikprijck** [comment]
Cool thanks @Widcket , I will close this but let me know if you need anything from me for this.
