### ISSUE TITLE
leave the audience blank by default

### ISSUE THREAD

**Issue by woloski** [auth0-samples/auth0-angular-samples#226]
the sample should work if I didn't create an API yet. It should just do auth. For that to happen we should leave an empty string in audience in `auth_config.json`. That should be the default (ie remove YOUR_API_IDENTIFIER).

**Comment by frederikprijck** [comment]
Hi @woloski ,

Leaving the audience blank in the config is something we can't do because our docs tooling relies on `YOUR_API_IDENTIFIER` to auto-fill the audience when downloading the sample from https://auth0.com/docs/quickstart/spa/angular/02-calling-an-api?download=true .

However, I have opened a PR to ensure we can run the sample without explicitly setting an `audience` but also without leaving it blank. This ensures our tooling still automatically fills in the `audience` when downloaded, but also ensures users can run the app when an `audience` is not explicitly specified.

That PR pretty much aligns our Angular Sample with how we solved this in the React sample: https://github.com/auth0-samples/auth0-react-samples/pull/222
