### ISSUE TITLE
Improve error message in alert output

### ISSUE THREAD

**Issue by aaronchilcott** [auth0-samples/auth0-angular-samples#27]
In the 00-Centralized-Login application there is an alert box with an vague error message which may be difficult to track down if you are unfamiliar with the code. 

I would suggest replacing with console.log(new Error(<meaningful message>)); To make the output less disruptive to program flow and to make it easier for developers to locate where the error is being generated from.

There is one instance of this in the following location: 
https://github.com/auth0-samples/auth0-angular-samples/blob/master/00-Centralized-Login/src/app/auth/auth.service.ts#L34

I assume there may be more.

**Comment by chenkie** [comment]
Thanks for your suggestion :) Since the sample apps are meant to be developer focused, the idea here is to draw attention to the fact that there is an error when one occurs, hence the alert.

I agree that it would be useful to show the full error object to give the dev a better idea of what's going on. I worry that if we just log it to the console then it will be easily missed when the sample app is first tried.

Perhaps logging it to the console and then an alert that says "Error: Check the console for details". 

What do you think?

**Comment by aaronchilcott** [comment]
You raise a good point. Perhaps, in that case an alert box is the way to go, however, some additional information about where the error is being generated from would definitely improve the usefulness of the alert. =)

**Comment by chenkie** [comment]
Cool :) Just pushed some changes to add the `console.log`. Thanks!
