### ISSUE TITLE
Login successfully while redirect to callback page --> Cannot match any routes. URL Segment: 'access_token'

### ISSUE THREAD

**Issue by kevinding0218** [auth0-samples/auth0-angular-samples#87]
Hello, I am following the official and current git repository to try performing the login with auto0, while my login authorization was successfully verified then there is some error happened when redirect back to my callback component.
Error Description: Cannot match any routes. URL Segment: 'access_token'

I've done a lot of research on that that I tried to use some other work around method like "handleRedirectWithHash" or "handleAuthenticationWithHash" in suggested fix while I am still getting the same error, the latest issue guides me here but it's still not solved on my end, I download the current "auth0-samples" project and run the first one "01-Login"  on my local and it stucks same at the callback component so the "handleAuthentication()" method never fires.

Is there a work around documentation for resolving this issue in Auth0? Or is there any setting in Auth0 that I am missing?
I am using Angular 5.2.1 with "auth0-js": "^9.2.0" and "auth0-lock": "^11.0.1" and I am using the default Angular path-based routing.

Any suggested fix would be much appreciated!

Many thanks,
Ran

**Comment by kevinding0218** [comment]
Hello, is there any suggestion over this one or maybe Angular 5 is not compatible with Auth0 for now?

**Comment by teaquack** [comment]
I had similar issue failing on callback. For me the callback url (http://localhost:4200/callback), which is where my Angular server was running was not the callback url (http://localhost:3000/callback), which auth0 uses by default. I fixed it by setting the callback url in the auth service config to localhost:4200, since that's where I have the running server.
Since you mention the access_token, it might have to do the clientId being different between the config in the app and auth0 account.
